# Generated by Django 3.0.5 on 2020-08-21 03:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='dateVisit',
            field=models.DateField(default=datetime.date(2020, 8, 21)),
        ),
    ]
