# Generated by Django 3.0.5 on 2020-08-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('companyName', models.CharField(max_length=100)),
                ('observation', models.CharField(blank=True, default='', max_length=200)),
                ('availability', models.CharField(choices=[('1', 'Available'), ('0', 'Unavailable')], default='1', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('observation', models.CharField(blank=True, default='', max_length=200)),
                ('availability', models.CharField(choices=[('1', 'Available'), ('0', 'Unavailable')], default='1', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('idCompany', models.CharField(blank=True, max_length=36)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('observation', models.CharField(blank=True, default='', max_length=200)),
                ('availability', models.CharField(choices=[('1', 'Available'), ('0', 'Unavailable')], default='1', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('idEmployee', models.CharField(max_length=36)),
                ('idTypeVisit', models.IntegerField(choices=[(1, 'Meeting'), (2, 'Package'), (3, 'General')], default=1)),
                ('idVisitor', models.CharField(blank=True, max_length=36)),
                ('dateVisit', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(1, 'Scheduled'), (2, 'Started'), (3, 'Finished'), (4, 'Cancelled')], default=1)),
            ],
        ),
    ]
