# Generated by Django 3.0.5 on 2020-09-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(default='12345678', max_length=100)),
                ('availability', models.CharField(choices=[('1', 'Available'), ('0', 'Unavailable')], default='1', max_length=1)),
            ],
        ),
    ]
