# Generated by Django 3.0.5 on 2020-08-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('availability', models.CharField(choices=[('1', 'Available'), ('0', 'Unavailable')], default='1', max_length=1)),
            ],
        ),
    ]
