# Generated by Django 3.0.5 on 2020-10-28 03:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('idEmployee', models.CharField(blank=True, max_length=36)),
                ('typeMessage', models.IntegerField(choices=[(1, 'Meeting'), (2, 'Package'), (3, 'General')], default=3)),
                ('dateMessage', models.DateField(default=datetime.date(2020, 10, 28))),
                ('hourMessage', models.TimeField(default=datetime.time(12, 0))),
            ],
        ),
    ]
