# Generated by Django 3.0.5 on 2020-08-22 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('personalCode', models.CharField(max_length=36, unique=True)),
                ('idCompany', models.CharField(blank=True, max_length=36)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('observation', models.CharField(blank=True, max_length=200)),
                ('availability', models.CharField(choices=[('1', 'Available'), ('0', 'Unavailable')], default='1', max_length=1)),
            ],
        ),
    ]
